/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tallergestion.moduloVehiculos;

import java.awt.CardLayout;
import java.awt.Container;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class FormularioVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form FormularioVehiculo
     */
    public FormularioVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Vehículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24)))); // NOI18N
        setName(""); // NOI18N
        setLayout(new java.awt.GridLayout(7, 2));

        lblIdCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIdCliente.setText("ID Cliente");
        add(lblIdCliente);
        add(txtIdCliente);

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMarca.setText("Marca");
        add(lblMarca);
        add(txtMarca);

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModelo.setText("Modelo");
        add(lblModelo);
        add(txtModelo);

        lblAño.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAño.setText("Año");
        add(lblAño);
        add(txtAño);

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlaca.setText("Placa");
        add(lblPlaca);
        add(txtPlaca);

        btnGuardar.setBackground(new java.awt.Color(0, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar);

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        add(btnCerrar);
        add(lblMensaje);

        getAccessibleContext().setAccessibleName("panelregistroVehiculo");
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Container contenedor = FormularioVehiculo.this.getParent();
        if (contenedor instanceof JPanel) {
        CardLayout cl = (CardLayout) contenedor.getLayout();
        cl.show(contenedor, "inicio");
}

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      registrarVehiculo();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    private void registrarVehiculo() {
      try {
        int idCliente = Integer.parseInt(txtIdCliente.getText().trim());
        String placa = txtPlaca.getText().trim();
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        int anio = Integer.parseInt(txtAño.getText().trim());
        
        if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }
      
        FileWriter fw = new FileWriter("vehiculos.txt", true);
        BufferedWriter bw = new BufferedWriter(fw);
        PrintWriter pw = new PrintWriter(bw);
        pw.println(idCliente + "," + placa + "," + marca + "," + modelo + "," + anio);
        pw.close();
        JOptionPane.showMessageDialog(this, "Vehículo registrado exitosamente.");
        limpiarCamposVehiculo();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID o año inválido.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el vehículo.");
    }
    }

    private void limpiarCamposVehiculo() {
    txtIdCliente.setText("");
    txtPlaca.setText("");
    txtMarca.setText("");
    txtModelo.setText("");
    txtAño.setText("");
    }
}
